### PR TITLE
Automated context creation

### LINKED ISSUE #14: Add Global Context
I think the best way to manage global state is by using Context API. If we decide to expand the app with new type of global data, we might want to make it fast and simple. I suggest making some sort of global context wrapper which gathers all of our contexts, then it wraps whole app with data. I suggest the Redux way, created from scratch with hooks (useReducer, dispatch, etc.)

### PR DESCRIPTION
**Pull request by ryszard-put**
This is the idea of fully automated context creation. Everything is explained in comments. If some concept is not clear, do not hesitate to ask

Resolves #14

### CODE REVIEW

**Comment by roertbb** [comment]
I'd like to start discussion with - do we need such a global state? and if yes - for what you'd like to use that? Also it's worth mention that if we'd handle some global state, it's might be worth it to incorporate redux/mobx and use their benefits over context... looking forward to discuss it tomorrow 😜and overall, nicely used and described concept of context 😉

**Comment by ryszard-put** [comment]
I think that global state may be useful mostly for managing state of map component (data like position, zoom, etc.), it could simplify use of modal components, and we could use it for sharing info about markers (share data between pages). I know that redux/mobx are good tools for state management, however I consider use of Context API and hooks as simplified version of these libraries. But as you said, we should discuss it tomorrow 😉

**Comment by roertbb** [comment]
As we've discussed - let's go for it 👍 looking forward to see concrete solution 😉

**Review by roertbb — APPROVED** [review]
lgtm 👍

**Pull request merged**
