### PR TITLE
Hide leaflet label

### PR DESCRIPTION
**Pull request by qwercik**
Hide and annoying leaflet label (that is absolute positioned and have big z-index value, so it was overlapping navbar).

### CODE REVIEW

**Comment by marcinlawnik** [comment]
If the leaflet label is hidden, then we should probably have a license/settings screen where libs that we used are displayed. Just my 2 cents.

**Comment by qwercik** [comment]
I can also simply move the label not to overlapping navbar, rather than hiding it.

**Comment by marcinlawnik** [comment]
Sure, both options are viable. See how jakdojade does it.
Screenshot_20191112-085019

**Comment by marcinlawnik** [comment]
The label is only visible when the map is almost fullscreen

**Pull request merged**
